# Generated by Django 2.2.5 on 2019-09-27 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_size', models.IntegerField(choices=[(1, 'Just me'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people')], help_text='Typically how many people you regularly purchase and prepare food with, including yourself.')),
                ('hasHouseholdBenefits', models.BooleanField()),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Must specify annual income if applicant does not have other household benefits (HEAP, SNAP, etc.)', max_digits=11)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5)),
                ('rent_or_own', models.CharField(choices=[('rent', 'Rent'), ('own', 'Own')], max_length=4)),
                ('street_address', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Make sure to enter a street number before the street name, for example 123 Main St', regex='^\\d+ .*')])),
                ('apartment_unit', models.CharField(blank=True, help_text="Skip this if you don't live in an apartment", max_length=10)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Your ZIP code must be exactly 5 digits', regex='^\\d{5}$')])),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Please use a valid phone number format such as 716-555-5555.', regex='^(\\d{10}|(\\d{3}\\-\\d{3}\\-\\d{4}))|(\\(\\d{3}\\)\\s?\\d{3}\\-\\d{4})')])),
                ('email_address', models.EmailField(blank=True, help_text='Optional to provide for status updates on your application', max_length=254)),
                ('account_holder', models.CharField(choices=[('me', 'Me'), ('landlord', 'My landlord'), ('other', 'Another person')], max_length=8)),
                ('account_first', models.CharField(max_length=100)),
                ('account_last', models.CharField(max_length=100)),
                ('account_middle', models.CharField(blank=True, max_length=5)),
                ('account_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Please enter only digits', regex='^\\d+$')])),
                ('legal_agreement', models.BooleanField()),
                ('signature', models.CharField(max_length=250)),
                ('income_photo', models.ImageField(blank=True, upload_to='income_docs')),
            ],
        ),
    ]
