# Generated by Django 2.2.5 on 2019-09-06 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=5)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_address', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(choices=[('WK', 'Every week'), ('TWK', 'Every two weeks'), ('TMO', 'Twice a month'), ('MO', 'Every month')], max_length=100)),
                ('income', models.IntegerField()),
                ('residency_photo', models.ImageField(upload_to='residency_docs')),
                ('income_photo', models.ImageField(upload_to='income_docs')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pathways.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_first', models.CharField(max_length=100)),
                ('account_middle', models.CharField(blank=True, default='', max_length=5)),
                ('account_last', models.CharField(max_length=100)),
                ('address_number', models.IntegerField()),
                ('address_street', models.CharField(max_length=100)),
                ('address_apartmentnum', models.CharField(max_length=100)),
                ('address_zip', models.IntegerField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pathways.Application')),
            ],
        ),
    ]
