# Generated by Django 2.2.5 on 2019-09-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Legal Agreement',
            new_name='legal_agreement',
        ),
    ]
