# Generated by Django 2.2.5 on 2019-09-09 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Please use a valid phone number format such as 716-555-5555.', regex='^((\\+[1])?\\d{10}|(\\d{3}\\-\\d{3}\\-\\d{4}))|(\\(\\d{3}\\)\\s?\\d{3}\\-\\d{4})')]),
        ),
    ]
