# Generated by Django 2.2.5 on 2019-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='residence_photo',
            field=models.ImageField(blank=True, upload_to='residence_docs'),
        ),
    ]
