# Generated by Django 2.2.6 on 2019-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_application_residence_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='benefits_photo',
            field=models.ImageField(blank=True, upload_to='benefits_docs'),
        ),
    ]
