# Generated by Django 2.2.5 on 2019-09-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_auto_20190926_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='account_holder',
            field=models.CharField(choices=[('me', 'Me'), ('landlord', 'My landlord'), ('other', 'Another person')], max_length=8),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residency_photo', models.ImageField(blank=True, upload_to='residency_docs')),
                ('income_photo', models.ImageField(blank=True, upload_to='income_docs')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pathways.Application')),
            ],
        ),
    ]
