# Generated by Django 2.2.5 on 2019-09-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_auto_20190909_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address_apartmentnum',
            new_name='address_apartment_number',
        ),
    ]
