# Generated by Django 2.2.5 on 2019-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0003_auto_20190909_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_apartment_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
