# Generated by Django 2.2.5 on 2019-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0003_auto_20190926_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
    ]
