# Generated by Django 2.2.5 on 2019-09-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0004_auto_20190909_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
