# Generated by Django 2.2.10 on 2020-02-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0004_auto_20191031_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='hasHouseholdBenefits',
            new_name='has_household_benefits',
        ),
    ]
