# Generated by Django 2.2.5 on 2019-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0005_auto_20190909_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='household',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='document',
            name='income_photo',
            field=models.ImageField(blank=True, upload_to='income_docs'),
        ),
        migrations.AlterField(
            model_name='document',
            name='residency_photo',
            field=models.ImageField(blank=True, upload_to='residency_docs'),
        ),
    ]
