# Generated by Django 2.2.10 on 2020-02-13 17:01

from django.db import migrations, models
import django.db.models.deletion
import pathways.models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0005_auto_20200211_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('income', 'Income'), ('benefits', 'Benefits'), ('residence', 'Residence')], max_length=9)),
                ('doc_file', models.FileField(blank=True, upload_to=pathways.models.path_and_rename, validators=[pathways.models.FileValidator(content_types=('image/jpeg', 'image/png', 'application/pdf', 'image/tiff'), max_size=4096000)])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathways.Application')),
            ],
        ),
    ]
