# Generated by Django 2.2.5 on 2019-09-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0006_auto_20190909_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='own_or_rent',
            field=models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent')], default='Own', max_length=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='household',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='document',
            name='income',
            field=models.PositiveIntegerField(),
        ),
    ]
