# Generated by Django 2.2.10 on 2020-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0006_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='household_size',
            field=models.IntegerField(choices=[(1, 'Just me'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people')], help_text='Typically how many people you regularly share living expenses with, including yourself. If you live with them, include children under 21, spouses/partners, and parents.'),
        ),
    ]
