# Generated by Django 2.2.12 on 2020-04-20 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathways.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathways', '0007_auto_20200227_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('income', 'Income'), ('benefits', 'Benefits'), ('residence', 'Residence')], max_length=9)),
                ('doc_file', models.TextField(blank=True, max_length=100, validators=[pathways.models.FileValidator(content_types=('image/jpeg', 'image/png', 'application/pdf', 'image/tiff'), max_size=4096000)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pathways.Application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalApplication',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('household_size', models.IntegerField(choices=[(1, 'Just me'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people')], help_text='Typically how many people you regularly share living expenses with, including yourself. If you live with them, include children under 21, spouses/partners, and parents.')),
                ('has_household_benefits', models.BooleanField()),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Must specify annual income if applicant does not have other household benefits (HEAP, SNAP, etc.)', max_digits=11)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5)),
                ('rent_or_own', models.CharField(choices=[('rent', 'Rent'), ('own', 'Own')], max_length=4)),
                ('street_address', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Make sure to enter a street number before the street name, for example 123 Main St', regex='^\\d+ .*')])),
                ('apartment_unit', models.CharField(blank=True, help_text="Skip this if you don't live in an apartment", max_length=10)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Your ZIP code must be exactly 5 digits', regex='^\\d{5}$')])),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Please use a valid phone number format such as 716-555-5555.', regex='^(\\d{10}|(\\d{3}\\-\\d{3}\\-\\d{4}))|(\\(\\d{3}\\)\\s?\\d{3}\\-\\d{4})')])),
                ('email_address', models.EmailField(blank=True, help_text='Optional to provide for status updates on your application', max_length=254)),
                ('account_holder', models.CharField(choices=[('me', 'Me'), ('landlord', 'My landlord'), ('other', 'Another person')], max_length=8)),
                ('account_first', models.CharField(max_length=100)),
                ('account_last', models.CharField(max_length=100)),
                ('account_middle', models.CharField(blank=True, max_length=5)),
                ('account_number', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Please enter only digits', regex='^\\d+$')])),
                ('legal_agreement', models.BooleanField()),
                ('signature', models.CharField(max_length=250)),
                ('income_photo', models.TextField(blank=True, max_length=100)),
                ('benefits_photo', models.TextField(blank=True, max_length=100)),
                ('residence_photo', models.TextField(blank=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical application',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
