# Generated by Django 2.2.12 on 2020-04-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0008_historicalapplication_historicaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='benefits_photo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='income_photo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='residence_photo',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='benefits_photo',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='income_photo',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='residence_photo',
        ),
    ]
