# Generated by Django 2.2.14 on 2020-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0010_forgivenessapplication_historicalforgivenessapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Discount Application', 'verbose_name_plural': 'Discount Applications'},
        ),
        migrations.AlterModelOptions(
            name='forgivenessapplication',
            options={'verbose_name': 'Amnesty Application', 'verbose_name_plural': 'Amnesty Applications'},
        ),
        migrations.AlterModelOptions(
            name='historicalapplication',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Discount Application'},
        ),
        migrations.AlterModelOptions(
            name='historicalforgivenessapplication',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Amnesty Application'},
        ),
        migrations.AddField(
            model_name='forgivenessapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter any notes for this case'),
        ),
        migrations.AddField(
            model_name='forgivenessapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('enrolled', 'Enrolled'), ('denied', 'Denied')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalforgivenessapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter any notes for this case'),
        ),
        migrations.AddField(
            model_name='historicalforgivenessapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('enrolled', 'Enrolled'), ('denied', 'Denied')], default='new', max_length=12),
        ),
    ]
