# Generated by Django 2.2.14 on 2020-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0011_auto_20200730_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Enter any notes for this case'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('enrolled', 'Enrolled'), ('denied', 'Denied')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Enter any notes for this case'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('enrolled', 'Enrolled'), ('denied', 'Denied')], default='new', max_length=12),
        ),
        migrations.AlterField(
            model_name='forgivenessapplication',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Enter any notes for this case'),
        ),
        migrations.AlterField(
            model_name='historicalforgivenessapplication',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Enter any notes for this case'),
        ),
    ]
