# Generated by Django 2.2.14 on 2020-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0012_auto_20200716_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcommunication',
            name='enrolled_in_amnesty_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='enrolled_in_discount_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemailcommunication',
            name='enrolled_in_amnesty_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemailcommunication',
            name='enrolled_in_discount_program',
            field=models.BooleanField(default=False),
        ),
    ]
