# Generated by Django 2.2.14 on 2020-07-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0014_auto_20200731_1025'),
        ('pathways', '0012_auto_20200731_1524'),
    ]

    operations = [
    ]
