sudo: required

dist: xenial

language: python

python:
  - "3.7"

node_js:
  - "12"

before_install:
  - pip install -U pip

install:
  - pip install pipenv
  - pipenv sync --dev
  - npm install
  - wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/chromedriver
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - export CHROME_BIN=chromium-browser

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv
    - node_modules
    - $HOME/.npm

before_script:
  - npm install -g gulp-cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - gulp
  - python manage.py collectstatic --noinput
  - python manage.py compress
  - coverage run manage.py test -v 2

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT