sudo: false

language: python

python:
  - "3.7"

node_js:
  - "12"

before_install:
  - pip install -U pip

install:
  - pip install pipenv
  - pipenv install
  - npm install

script:
  - coverage run manage.py test